import AsyncStorage from '@react-native-async-storage/async-storage';

interface UserProfile {
  email: string;
  password: string;
  firstName: string;
  lastName: string;
  phone: string;
  userType: 'owner' | 'sitter';
  profilePhoto?: string;
  address?: string;
  city?: string;
  state?: string;
  zipCode?: string;
  latitude?: number;
  longitude?: number;
  dogName?: string;
  dogBreed?: string;
  dogAge?: string;
  dogWeight?: string;
  dogSize?: 'small' | 'medium' | 'large' | 'extra_large';
  experience?: string;
  homeType?: 'apartment' | 'house' | 'house_with_yard';
  hasOtherPets?: boolean;
  maxDistance?: number;
  preferredSizes?: string[];
  needsSitting?: boolean;
  needsWalking?: boolean;
  providesSitting?: boolean;
  providesWalking?: boolean;
}

const sampleOwners: UserProfile[] = [
  {
    email: 'sarah.owner@test.com',
    password: 'password123',
    firstName: 'Sarah',
    lastName: 'Johnson',
    phone: '650-555-0101',
    userType: 'owner',
    profilePhoto: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=400',
    address: '879 Moreno Ave',
    city: 'Palo Alto',
    state: 'CA',
    zipCode: '94303',
    latitude: 37.4419,
    longitude: -122.1430,
    dogName: 'Buddy',
    dogBreed: 'Golden Retriever',
    dogAge: '3 years',
    dogWeight: '65 lbs',
    dogSize: 'large',
    dogTemperament: 'Friendly and energetic',
    dogHealthIssues: 'None',
    dogAllergies: 'None',
    dogExerciseNeeds: 'High - needs 2 walks daily',
    dogTrainingLevel: 'Well-trained',
    dogVaccinations: 'Up to date',
    dogDiet: 'Premium dry food, twice daily',
    needsSitting: true,
    needsWalking: true,
    emergencyContact: '650-555-0100',
  },
  {
    email: 'mike.chen@test.com',
    password: 'password123',
    firstName: 'Mike',
    lastName: 'Chen',
    phone: '650-555-0102',
    userType: 'owner',
    profilePhoto: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=400',
    address: '1065 Greenwood Ave',
    city: 'Palo Alto',
    state: 'CA',
    zipCode: '94301',
    latitude: 37.4475,
    longitude: -122.1610,
    dogName: 'Luna',
    dogBreed: 'French Bulldog',
    dogAge: '2 years',
    dogWeight: '25 lbs',
    dogSize: 'small',
    dogTemperament: 'Playful and affectionate',
    dogHealthIssues: 'Sensitive to heat',
    dogAllergies: 'Chicken',
    dogExerciseNeeds: 'Moderate - short walks',
    dogTrainingLevel: 'Basic training',
    dogVaccinations: 'Up to date',
    dogDiet: 'Grain-free kibble',
    needsSitting: false,
    needsWalking: true,
    emergencyContact: '650-555-0103',
  },
  {
    email: 'jennifer.martinez@test.com',
    password: 'password123',
    firstName: 'Jennifer',
    lastName: 'Martinez',
    phone: '650-555-0104',
    userType: 'owner',
    profilePhoto: 'https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?w=400',
    address: '2508 Ramona St',
    city: 'Palo Alto',
    state: 'CA',
    zipCode: '94301',
    latitude: 37.4321,
    longitude: -122.1542,
    dogName: 'Max',
    dogBreed: 'German Shepherd',
    dogAge: '4 years',
    dogWeight: '80 lbs',
    dogSize: 'large',
    dogTemperament: 'Protective and loyal',
    dogHealthIssues: 'Hip dysplasia - needs gentle exercise',
    dogAllergies: 'None',
    dogExerciseNeeds: 'Moderate - avoid jumping',
    dogTrainingLevel: 'Highly trained, knows commands',
    dogVaccinations: 'Up to date',
    dogDiet: 'Joint support formula',
    needsSitting: true,
    needsWalking: true,
    emergencyContact: '650-555-0105',
  },
  {
    email: 'david.patel@test.com',
    password: 'password123',
    firstName: 'David',
    lastName: 'Patel',
    phone: '650-555-0106',
    userType: 'owner',
    profilePhoto: 'https://images.unsplash.com/photo-1568572933382-74d440642117?w=400',
    address: '318 Parkside Dr',
    city: 'Palo Alto',
    state: 'CA',
    zipCode: '94306',
    latitude: 37.4200,
    longitude: -122.1350,
    dogName: 'Bella',
    dogBreed: 'Labrador Retriever',
    dogAge: '5 years',
    dogWeight: '70 lbs',
    dogSize: 'large',
    dogTemperament: 'Gentle and loving',
    dogHealthIssues: 'None',
    dogAllergies: 'None',
    dogExerciseNeeds: 'High - loves swimming',
    dogTrainingLevel: 'Well-trained',
    dogVaccinations: 'Up to date',
    dogDiet: 'Large breed formula',
    needsSitting: true,
    needsWalking: false,
    emergencyContact: '650-555-0107',
  },
  {
    email: 'amanda.wong@test.com',
    password: 'password123',
    firstName: 'Amanda',
    lastName: 'Wong',
    phone: '650-555-0108',
    userType: 'owner',
    profilePhoto: 'https://images.unsplash.com/photo-1561037404-61cd46aa615b?w=400',
    address: '3773 Redwood Cir',
    city: 'Palo Alto',
    state: 'CA',
    zipCode: '94306',
    latitude: 37.4150,
    longitude: -122.1280,
    dogName: 'Charlie',
    dogBreed: 'Beagle',
    dogAge: '3 years',
    dogWeight: '30 lbs',
    dogSize: 'medium',
    dogTemperament: 'Curious and friendly',
    dogHealthIssues: 'None',
    dogAllergies: 'None',
    dogExerciseNeeds: 'High - loves to explore',
    dogTrainingLevel: 'Moderate - can be stubborn',
    dogVaccinations: 'Up to date',
    dogDiet: 'Standard kibble',
    needsSitting: true,
    needsWalking: true,
    emergencyContact: '650-555-0109',
  },
  {
    email: 'robert.taylor@test.com',
    password: 'password123',
    firstName: 'Robert',
    lastName: 'Taylor',
    phone: '650-555-0110',
    userType: 'owner',
    profilePhoto: 'https://images.unsplash.com/photo-1552053831-71594a27632d?w=400',
    address: '611 E Meadow Dr',
    city: 'Palo Alto',
    state: 'CA',
    zipCode: '94306',
    latitude: 37.4180,
    longitude: -122.1300,
    dogName: 'Daisy',
    dogBreed: 'Border Collie',
    dogAge: '2 years',
    dogWeight: '45 lbs',
    dogSize: 'medium',
    dogTemperament: 'Intelligent and active',
    dogHealthIssues: 'None',
    dogAllergies: 'None',
    dogExerciseNeeds: 'Very high - needs mental stimulation',
    dogTrainingLevel: 'Highly trained, knows tricks',
    dogVaccinations: 'Up to date',
    dogDiet: 'High-protein formula',
    needsSitting: false,
    needsWalking: true,
    emergencyContact: '650-555-0111',
  },
  {
    email: 'lisa.nguyen@test.com',
    password: 'password123',
    firstName: 'Lisa',
    lastName: 'Nguyen',
    phone: '650-555-0112',
    userType: 'owner',
    profilePhoto: 'https://images.unsplash.com/photo-1576201836106-db1758fd1c97?w=400',
    address: '754 Holly Oak Dr',
    city: 'Palo Alto',
    state: 'CA',
    zipCode: '94303',
    latitude: 37.4450,
    longitude: -122.1380,
    dogName: 'Rocky',
    dogBreed: 'Bulldog',
    dogAge: '4 years',
    dogWeight: '50 lbs',
    dogSize: 'medium',
    dogTemperament: 'Calm and friendly',
    dogHealthIssues: 'Breathing issues - avoid overexertion',
    dogAllergies: 'Beef',
    dogExerciseNeeds: 'Low - short walks only',
    dogTrainingLevel: 'Basic training',
    dogVaccinations: 'Up to date',
    dogDiet: 'Special diet for sensitive stomach',
    needsSitting: true,
    needsWalking: true,
    emergencyContact: '650-555-0113',
  },
  {
    email: 'james.anderson@test.com',
    password: 'password123',
    firstName: 'James',
    lastName: 'Anderson',
    phone: '650-555-0114',
    userType: 'owner',
    profilePhoto: 'https://images.unsplash.com/photo-1558788353-f76d92427f16?w=400',
    address: '851 Colorado Ave',
    city: 'Palo Alto',
    state: 'CA',
    zipCode: '94303',
    latitude: 37.4280,
    longitude: -122.1420,
    dogName: 'Cooper',
    dogBreed: 'Australian Shepherd',
    dogAge: '3 years',
    dogWeight: '55 lbs',
    dogSize: 'medium',
    dogTemperament: 'Energetic and smart',
    dogHealthIssues: 'None',
    dogAllergies: 'None',
    dogExerciseNeeds: 'Very high - needs lots of activity',
    dogTrainingLevel: 'Well-trained, agility experience',
    dogVaccinations: 'Up to date',
    dogDiet: 'Active dog formula',
    needsSitting: true,
    needsWalking: true,
    emergencyContact: '650-555-0115',
  },
  {
    email: 'michelle.brown@test.com',
    password: 'password123',
    firstName: 'Michelle',
    lastName: 'Brown',
    phone: '650-555-0116',
    userType: 'owner',
    profilePhoto: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=400',
    address: '270 Campesino Ave',
    city: 'Palo Alto',
    state: 'CA',
    zipCode: '94306',
    latitude: 37.4100,
    longitude: -122.1250,
    dogName: 'Milo',
    dogBreed: 'Pomeranian',
    dogAge: '2 years',
    dogWeight: '12 lbs',
    dogSize: 'small',
    dogTemperament: 'Energetic and vocal',
    dogHealthIssues: 'None',
    dogAllergies: 'None',
    dogExerciseNeeds: 'Moderate - indoor play sufficient',
    dogTrainingLevel: 'Basic training',
    dogVaccinations: 'Up to date',
    dogDiet: 'Small breed formula',
    needsSitting: true,
    needsWalking: false,
    emergencyContact: '650-555-0117',
  },
  {
    email: 'kevin.lee@test.com',
    password: 'password123',
    firstName: 'Kevin',
    lastName: 'Lee',
    phone: '650-555-0118',
    userType: 'owner',
    profilePhoto: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=400',
    address: '2896 Waverley St',
    city: 'Palo Alto',
    state: 'CA',
    zipCode: '94306',
    latitude: 37.4220,
    longitude: -122.1320,
    dogName: 'Sadie',
    dogBreed: 'Corgi',
    dogAge: '1 year',
    dogWeight: '28 lbs',
    dogSize: 'small',
    dogTemperament: 'Playful and social',
    dogHealthIssues: 'None',
    dogAllergies: 'None',
    dogExerciseNeeds: 'Moderate - loves walks',
    dogTrainingLevel: 'In training - puppy class',
    dogVaccinations: 'Up to date',
    dogDiet: 'Puppy formula',
    needsSitting: false,
    needsWalking: true,
    emergencyContact: '650-555-0119',
  },
];

const sampleSitters: UserProfile[] = [
  {
    email: 'alex.rodriguez@test.com',
    password: 'password123',
    firstName: 'Alex',
    lastName: 'Rodriguez',
    phone: '650-555-0201',
    userType: 'sitter',
    profilePhoto: 'https://randomuser.me/api/portraits/men/32.jpg',
    address: '2225 Webster St',
    city: 'Palo Alto',
    state: 'CA',
    zipCode: '94301',
    latitude: 37.4350,
    longitude: -122.1500,
    experience: '5+ years of professional dog sitting',
    homeType: 'house_with_yard',
    hasOtherPets: true,
    maxDistance: 10,
    preferredSizes: ['small', 'medium', 'large'],
    providesSitting: true,
    providesWalking: true,
    emergencyContact: '650-555-0200',
    preferredStartTime: '8:00 AM',
    preferredEndTime: '6:00 PM',
    availableDays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
    shortNotice: true,
    overnightCare: true,
    weekendCare: false,
    holidayCare: true,
  },
  {
    email: 'jenny.kim@test.com',
    password: 'password123',
    firstName: 'Jenny',
    lastName: 'Kim',
    phone: '650-555-0202',
    userType: 'sitter',
    profilePhoto: 'https://randomuser.me/api/portraits/women/44.jpg',
    address: '553 Hilbar Ln',
    city: 'Palo Alto',
    state: 'CA',
    zipCode: '94303',
    latitude: 37.4380,
    longitude: -122.1450,
    experience: '2 years - great with small dogs',
    homeType: 'apartment',
    hasOtherPets: false,
    maxDistance: 5,
    preferredSizes: ['small', 'medium'],
    providesSitting: false,
    providesWalking: true,
    emergencyContact: '650-555-0203',
    preferredStartTime: '7:00 AM',
    preferredEndTime: '8:00 PM',
    availableDays: ['monday', 'wednesday', 'friday', 'saturday', 'sunday'],
    shortNotice: false,
    overnightCare: false,
    weekendCare: true,
    holidayCare: false,
  },
  {
    email: 'marcus.thompson@test.com',
    password: 'password123',
    firstName: 'Marcus',
    lastName: 'Thompson',
    phone: '650-555-0204',
    userType: 'sitter',
    profilePhoto: 'https://randomuser.me/api/portraits/men/52.jpg',
    address: '2070 Edgewood Dr',
    city: 'Palo Alto',
    state: 'CA',
    zipCode: '94303',
    latitude: 37.4290,
    longitude: -122.1370,
    experience: '7 years - certified dog trainer',
    homeType: 'house_with_yard',
    hasOtherPets: true,
    maxDistance: 15,
    preferredSizes: ['medium', 'large', 'extra_large'],
    providesSitting: true,
    providesWalking: true,
    emergencyContact: '650-555-0205',
    preferredStartTime: '6:00 AM',
    preferredEndTime: '7:00 PM',
    availableDays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday'],
    shortNotice: true,
    overnightCare: true,
    weekendCare: true,
    holidayCare: true,
  },
  {
    email: 'emily.davis@test.com',
    password: 'password123',
    firstName: 'Emily',
    lastName: 'Davis',
    phone: '650-555-0206',
    userType: 'sitter',
    profilePhoto: 'https://randomuser.me/api/portraits/women/68.jpg',
    address: '1324 Dana Ave',
    city: 'Palo Alto',
    state: 'CA',
    zipCode: '94301',
    latitude: 37.4410,
    longitude: -122.1520,
    experience: '3 years - veterinary assistant',
    homeType: 'house',
    hasOtherPets: false,
    maxDistance: 8,
    preferredSizes: ['small', 'medium', 'large'],
    providesSitting: true,
    providesWalking: true,
    emergencyContact: '650-555-0207',
    preferredStartTime: '9:00 AM',
    preferredEndTime: '5:00 PM',
    availableDays: ['tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    shortNotice: false,
    overnightCare: true,
    weekendCare: true,
    holidayCare: false,
  },
  {
    email: 'carlos.garcia@test.com',
    password: 'password123',
    firstName: 'Carlos',
    lastName: 'Garcia',
    phone: '650-555-0208',
    userType: 'sitter',
    profilePhoto: 'https://randomuser.me/api/portraits/men/22.jpg',
    address: '846 Lytton Ave',
    city: 'Palo Alto',
    state: 'CA',
    zipCode: '94301',
    latitude: 37.4440,
    longitude: -122.1580,
    experience: '4 years - loves active dogs',
    homeType: 'house_with_yard',
    hasOtherPets: true,
    maxDistance: 12,
    preferredSizes: ['medium', 'large', 'extra_large'],
    providesSitting: true,
    providesWalking: true,
    emergencyContact: '650-555-0209',
    preferredStartTime: '7:00 AM',
    preferredEndTime: '8:00 PM',
    availableDays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
    shortNotice: true,
    overnightCare: false,
    weekendCare: false,
    holidayCare: true,
  },
  {
    email: 'sophia.wilson@test.com',
    password: 'password123',
    firstName: 'Sophia',
    lastName: 'Wilson',
    phone: '650-555-0210',
    userType: 'sitter',
    profilePhoto: 'https://randomuser.me/api/portraits/women/24.jpg',
    address: '880 Center Dr',
    city: 'Palo Alto',
    state: 'CA',
    zipCode: '94301',
    latitude: 37.4460,
    longitude: -122.1600,
    experience: '6 years - specializes in senior dogs',
    homeType: 'house',
    hasOtherPets: false,
    maxDistance: 6,
    preferredSizes: ['small', 'medium'],
    providesSitting: true,
    providesWalking: true,
    emergencyContact: '650-555-0211',
    preferredStartTime: '8:00 AM',
    preferredEndTime: '6:00 PM',
    availableDays: ['monday', 'wednesday', 'friday', 'saturday'],
    shortNotice: false,
    overnightCare: true,
    weekendCare: true,
    holidayCare: true,
  },
  {
    email: 'ryan.miller@test.com',
    password: 'password123',
    firstName: 'Ryan',
    lastName: 'Miller',
    phone: '650-555-0212',
    userType: 'sitter',
    profilePhoto: 'https://randomuser.me/api/portraits/men/46.jpg',
    address: '201 Walter Hays Dr',
    city: 'Palo Alto',
    state: 'CA',
    zipCode: '94303',
    latitude: 37.4250,
    longitude: -122.1340,
    experience: '1 year - college student, loves dogs',
    homeType: 'apartment',
    hasOtherPets: false,
    maxDistance: 7,
    preferredSizes: ['small', 'medium'],
    providesSitting: false,
    providesWalking: true,
    emergencyContact: '650-555-0213',
    preferredStartTime: '6:00 AM',
    preferredEndTime: '10:00 AM',
    availableDays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
    shortNotice: true,
    overnightCare: false,
    weekendCare: false,
    holidayCare: false,
  },
  {
    email: 'priya.sharma@test.com',
    password: 'password123',
    firstName: 'Priya',
    lastName: 'Sharma',
    phone: '650-555-0214',
    userType: 'sitter',
    profilePhoto: 'https://randomuser.me/api/portraits/women/89.jpg',
    address: '159 Walter Hays Dr',
    city: 'Palo Alto',
    state: 'CA',
    zipCode: '94303',
    latitude: 37.4260,
    longitude: -122.1330,
    experience: '8+ years - former shelter volunteer',
    homeType: 'house_with_yard',
    hasOtherPets: true,
    maxDistance: 10,
    preferredSizes: ['small', 'medium', 'large', 'extra_large'],
    providesSitting: true,
    providesWalking: true,
    emergencyContact: '650-555-0215',
    preferredStartTime: '7:00 AM',
    preferredEndTime: '7:00 PM',
    availableDays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    shortNotice: true,
    overnightCare: true,
    weekendCare: true,
    holidayCare: true,
  },
  {
    email: 'nathan.clark@test.com',
    password: 'password123',
    firstName: 'Nathan',
    lastName: 'Clark',
    phone: '650-555-0216',
    userType: 'sitter',
    profilePhoto: 'https://randomuser.me/api/portraits/men/71.jpg',
    address: '3131 Greer Rd',
    city: 'Palo Alto',
    state: 'CA',
    zipCode: '94303',
    latitude: 37.4120,
    longitude: -122.1260,
    experience: '3 years - work from home, flexible schedule',
    homeType: 'house',
    hasOtherPets: true,
    maxDistance: 9,
    preferredSizes: ['medium', 'large'],
    providesSitting: true,
    providesWalking: true,
    emergencyContact: '650-555-0217',
    preferredStartTime: '8:00 AM',
    preferredEndTime: '8:00 PM',
    availableDays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
    shortNotice: true,
    overnightCare: false,
    weekendCare: false,
    holidayCare: false,
  },
  {
    email: 'olivia.martinez@test.com',
    password: 'password123',
    firstName: 'Olivia',
    lastName: 'Martinez',
    phone: '650-555-0218',
    userType: 'sitter',
    profilePhoto: 'https://randomuser.me/api/portraits/women/17.jpg',
    address: '2225 Webster St',
    city: 'Palo Alto',
    state: 'CA',
    zipCode: '94301',
    latitude: 37.4355,
    longitude: -122.1505,
    experience: '5 years - patient with anxious dogs',
    homeType: 'apartment',
    hasOtherPets: false,
    maxDistance: 5,
    preferredSizes: ['small'],
    providesSitting: true,
    providesWalking: true,
    emergencyContact: '650-555-0219',
    preferredStartTime: '9:00 AM',
    preferredEndTime: '6:00 PM',
    availableDays: ['saturday', 'sunday'],
    shortNotice: false,
    overnightCare: true,
    weekendCare: true,
    holidayCare: false,
  },
];

interface StoredUser {
  id: string;
  email: string;
  password: string;
  profile: UserProfile;
  createdAt: string;
  updatedAt: string;
}

export const generateTestUsers = async (): Promise<void> => {
  try {
    const allTestUsers = [...sampleOwners, ...sampleSitters];

    // Get existing users
    const existingUsersData = await AsyncStorage.getItem('pawpair_users');
    const existingUsers: StoredUser[] = existingUsersData ? JSON.parse(existingUsersData) : [];

    // Add test users that don't already exist
    const existingEmails = existingUsers.map((user: StoredUser) => user.email);
    const newUsers = allTestUsers.filter(user => !existingEmails.includes(user.email));

    if (newUsers.length > 0) {
      // Convert UserProfile to StoredUser format
      const storedNewUsers: StoredUser[] = newUsers.map((user, index) => ({
        id: Date.now().toString() + index.toString() + Math.random().toString(36).substr(2, 9),
        email: user.email,
        password: user.password,
        profile: user,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
      }));

      const updatedUsers = [...existingUsers, ...storedNewUsers];
      await AsyncStorage.setItem('pawpair_users', JSON.stringify(updatedUsers));
      console.log(`✅ Added ${newUsers.length} test users`);
    } else {
      console.log('✅ All test users already exist');
    }
  } catch (error) {
    console.error('❌ Error generating test users:', error);
  }
};

export const clearAllUsers = async (): Promise<void> => {
  try {
    await AsyncStorage.removeItem('pawpair_users');
    await AsyncStorage.removeItem('pawpair_current_user');
    console.log('Cleared all users');
  } catch (error) {
    console.error('Error clearing users:', error);
  }
};

export const listAllUsers = async (): Promise<UserProfile[]> => {
  try {
    const usersData = await AsyncStorage.getItem('pawpair_users');
    if (!usersData) return [];

    const storedUsers: StoredUser[] = JSON.parse(usersData);
    // Return just the profiles
    return storedUsers.map(user => user.profile);
  } catch (error) {
    console.error('Error listing users:', error);
    return [];
  }
};